'use strict';

// scripts/render-crontab.js
//
// The crontab is GENERATED from lib/job-registry.js. A registry that merely
// describes a hand-maintained crontab would be a third source of truth.
//
// This is also the only mechanism that catches a line hand-added or deleted on
// the droplet. "A job absent from the registry alerts" only catches a job that
// RAN AND LOGGED under an unknown name — the already-visible case. A crontab
// line that never runs and never logs is the invisible half, and only a diff
// against the rendered output can see it.
//
//   node scripts/render-crontab.js            # print the crontab
//   node scripts/render-crontab.js --check    # diff against `crontab -l`, exit 1 on drift
//   node scripts/render-crontab.js --smoke    # offline self-test
//
// Deploy:  node scripts/render-crontab.js | crontab -

const { JOBS } = require('../lib/job-registry');

const ROOT = process.env.HEMNET_ROOT || '/opt/hemnet-cohort-tracker';

const HEADER = [
  '# ---------------------------------------------------------------',
  '# GENERATED by scripts/render-crontab.js from lib/job-registry.js',
  '# Do NOT hand-edit. `node scripts/render-crontab.js --check` fails on drift',
  '# and runs as an assertion in the daily digest.',
  '# Regenerate:  node scripts/render-crontab.js | crontab -',
  '# ---------------------------------------------------------------',
];

// renderLine(name, rec, root) — one crontab line. Order is fixed:
//   <cron> [cd <root> && ][ENV=v ]<command>[ >> <log> 2>&1]
function renderLine(name, rec, root) {
  const prefix = rec.cwd === false ? '' : `cd ${root} && `;
  const env = rec.env
    ? Object.entries(rec.env).map(([k, v]) => `${k}=${v}`).join(' ') + ' '
    : '';
  let line = `${rec.cron} ${prefix}${env}${rec.command}`;
  if (rec.log) line += ` >> ${rec.log} 2>&1`;
  return line;
}

// renderCrontab(jobs, root) — sorted by job name so the output is stable and
// diffs are readable. Trailing newline is required: cron silently ignores a
// final line with no newline after it.
function renderCrontab(jobs, root) {
  const names = Object.keys(jobs).filter(n => jobs[n].cron).sort();
  const lines = names.map(n => renderLine(n, jobs[n], root));
  return [...HEADER, '', ...lines, ''].join('\n');
}

// diffCrontab(rendered, live) — set comparison over schedule lines only.
// Comments and blanks are not schedule, so they never trip drift detection.
function significant(text) {
  return (text || '')
    .split('\n')
    .map(l => l.replace(/\s+$/, ''))
    .filter(l => l.trim() && !l.trim().startsWith('#'));
}

function diffCrontab(rendered, live) {
  const want = significant(rendered);
  const have = significant(live);
  const haveSet = new Set(have);
  const wantSet = new Set(want);
  const missing = want.filter(l => !haveSet.has(l));   // in registry, not on the box
  const extra = have.filter(l => !wantSet.has(l));     // on the box, not in the registry
  return { inSync: missing.length === 0 && extra.length === 0, missing, extra };
}

module.exports = { renderCrontab, renderLine, diffCrontab, HEADER, ROOT };

if (require.main === module && !process.argv.includes('--smoke')) {
  if (process.argv.includes('--check')) {
    const { execFileSync } = require('child_process');
    let live = '';
    try {
      live = execFileSync('crontab', ['-l'], { encoding: 'utf8' });
    } catch (err) {
      console.error(`render-crontab --check: could not read the live crontab: ${err.message}`);
      process.exit(1);
    }
    const d = diffCrontab(renderCrontab(JOBS, ROOT), live);
    if (d.inSync) {
      console.log('crontab in sync with lib/job-registry.js');
      process.exit(0);
    }
    console.error('CRONTAB DRIFT detected:');
    for (const l of d.missing) console.error(`  MISSING (in registry, not on the box): ${l}`);
    for (const l of d.extra) console.error(`  EXTRA   (on the box, not in registry):  ${l}`);
    process.exit(1);
  }
  process.stdout.write(renderCrontab(JOBS, ROOT));
}

// ---------------------------------------------------------------
//   node scripts/render-crontab.js --smoke
// ---------------------------------------------------------------
if (require.main === module && process.argv.includes('--smoke')) {
  const assert = require('assert');
  const { renderCrontab, renderLine, diffCrontab } = module.exports;
  const { JOBS } = require('../lib/job-registry');
  const ROOT = '/opt/hemnet-cohort-tracker';
  let pass = 0, fail = 0;
  const check = (name, fn) => {
    try { fn(); pass++; }
    catch (e) { console.error(`SMOKE FAIL [${name}]: ${e.message}`); fail++; }
  };

  check('a plain node job renders schedule + cd + command', () => {
    const line = renderLine('cohort-create', { cron: '0 6 * * 1', command: 'node cohort-create.js' }, ROOT);
    assert.strictEqual(line, '0 6 * * 1 cd /opt/hemnet-cohort-tracker && node cohort-create.js');
  });

  check('a log path renders the append + stderr redirect', () => {
    const line = renderLine('cohort-track', {
      cron: '0 22 */2 * *', command: 'node cohort-track.js', log: '/var/log/hemnet/cohort-track.log',
    }, ROOT);
    assert.strictEqual(line,
      '0 22 */2 * * cd /opt/hemnet-cohort-tracker && node cohort-track.js >> /var/log/hemnet/cohort-track.log 2>&1');
  });

  check('env vars render before the command', () => {
    const line = renderLine('premarket-flow-measure', {
      cron: '50 8 * * 1', command: 'node scripts/premarket-flow-measure.js',
      env: { SCRAPE_FORCE_OXYLABS: '1' }, log: '/var/log/hemnet/premarket-flow-measure.log',
    }, ROOT);
    assert.ok(line.includes('&& SCRAPE_FORCE_OXYLABS=1 node scripts/premarket-flow-measure.js'),
      `env prefix misplaced: ${line}`);
  });

  check('cwd:false omits the cd prefix (the find lines run from anywhere)', () => {
    const line = renderLine('soldmatch-cache-retention', {
      cron: '30 6 * * *', cwd: false, command: "find /x -mtime +3 -delete", log: '/var/log/hemnet/retention.log',
    }, ROOT);
    assert.strictEqual(line, "30 6 * * * find /x -mtime +3 -delete >> /var/log/hemnet/retention.log 2>&1");
    assert.ok(!line.includes('cd '), 'cwd:false must not emit a cd');
  });

  check('an unscheduled job is never emitted', () => {
    const out = renderCrontab(JOBS, ROOT);
    assert.ok(!out.includes('sfpl-region-snapshot'),
      'a registry entry with no cron must not reach the crontab');
  });

  check('every scheduled job appears exactly once', () => {
    const out = renderCrontab(JOBS, ROOT);
    const body = out.split('\n').filter(l => l.trim() && !l.startsWith('#'));
    const scheduled = Object.values(JOBS).filter(r => r.cron).length;
    assert.strictEqual(body.length, scheduled, `expected ${scheduled} lines, got ${body.length}`);
  });

  check('the proven live drift is present in the output', () => {
    const out = renderCrontab(JOBS, ROOT);
    assert.ok(out.includes('node scripts/premarket-quality-measure.js'),
      'premarket-quality-measure is deployed and running weekly — it must be rendered');
  });

  check('output is deterministic — rendering twice is identical', () => {
    assert.strictEqual(renderCrontab(JOBS, ROOT), renderCrontab(JOBS, ROOT));
  });

  check('output carries a do-not-hand-edit header and ends with a newline', () => {
    const out = renderCrontab(JOBS, ROOT);
    assert.ok(out.startsWith('#'), 'must start with a comment header');
    assert.ok(/GENERATED/.test(out), 'header must say it is generated');
    assert.ok(out.endsWith('\n'), 'crontab files must end with a newline or cron ignores the last line');
  });

  check('diffCrontab: identical input is in sync', () => {
    const out = renderCrontab(JOBS, ROOT);
    const d = diffCrontab(out, out);
    assert.strictEqual(d.inSync, true);
    assert.deepStrictEqual(d.missing, []);
    assert.deepStrictEqual(d.extra, []);
  });

  // The invisible half: a line hand-DELETED on the droplet never runs and never
  // logs, so no amount of log-watching can see it. Only this diff can.
  check('diffCrontab: a hand-deleted line is reported missing', () => {
    const out = renderCrontab(JOBS, ROOT);
    const lines = out.split('\n').filter(l => l.trim() && !l.startsWith('#'));
    const live = lines.slice(1).join('\n') + '\n';
    const d = diffCrontab(out, live);
    assert.strictEqual(d.inSync, false);
    assert.deepStrictEqual(d.missing, [lines[0]]);
  });

  check('diffCrontab: a hand-added line is reported extra', () => {
    const out = renderCrontab(JOBS, ROOT);
    const live = out + '0 0 * * * node /opt/rogue.js\n';
    const d = diffCrontab(out, live);
    assert.strictEqual(d.inSync, false);
    assert.deepStrictEqual(d.extra, ['0 0 * * * node /opt/rogue.js']);
  });

  check('diffCrontab ignores comments and blank lines on both sides', () => {
    const out = renderCrontab(JOBS, ROOT);
    const live = '# a human note\n\n' + out.split('\n').filter(l => l.trim() && !l.startsWith('#')).join('\n') + '\n';
    assert.strictEqual(diffCrontab(out, live).inSync, true,
      'comments are not schedule; they must not trip drift detection');
  });

  console.log(`smoke: ${pass} pass, ${fail} fail`);
  process.exit(fail === 0 ? 0 : 1);
}
